In [4]:
pip install numpy

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/__main__.py", line 9, in <module>
    if sys.path[0] in ("", os.getcwd()):
PermissionError: [Errno 1] Operation not permitted
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
data = np.random.rand(2,3,4)
#the shape is in the bracket

In [7]:
data

array([[[0.46593925, 0.30443221, 0.3975952 , 0.51200312],
        [0.68812814, 0.58120092, 0.73745315, 0.4889169 ],
        [0.35241031, 0.35594832, 0.11511485, 0.07879824]],

       [[0.80733593, 0.24122712, 0.75696663, 0.64993889],
        [0.93817447, 0.89036254, 0.51819345, 0.85084378],
        [0.46051214, 0.23137149, 0.23678876, 0.70749523]]])

In [12]:
zeros = np.zeros([2,2,2])
full = np.full([2,2,2] ,7)
ones = np.ones([2,2,2])

#the data can not be in  the same memory space as zeros and full arrays 

In [13]:
type(zeros)

numpy.ndarray

In [16]:
shape = data.shape
size = data.size
types = data.dtype

#they are not array values so do not  use bracket in the end of syntax


In [18]:

arr = data[0]
slicer = data[0][0:2] #this is for grabbing the specfic poitns we want 
reverse = data[-1]
singleval = data[0][0]
singleval


array([0.46593925, 0.30443221, 0.3975952 , 0.51200312])

In [19]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)


In [22]:
add = np.add(list1,list2)
dot = np.dot(list2,list1)
dot

#rest all multiplication and all are the same  as dot product

#the following are the other functions of the  numpy library that we will use in this : sqrt,abs,power,log,exo,min,max 


2.1040692325682064

In [27]:
data[0][0][0] = 700

In [24]:
data.sort()

In [28]:
data

array([[[7.00000000e+02, 3.97595203e-01, 4.65939255e-01, 5.12003117e-01],
        [4.88916901e-01, 5.81200916e-01, 6.88128144e-01, 7.37453149e-01],
        [7.87982363e-02, 1.15114850e-01, 3.52410310e-01, 3.55948323e-01]],

       [[2.41227122e-01, 6.49938887e-01, 7.56966633e-01, 8.07335927e-01],
        [5.18193455e-01, 8.50843781e-01, 8.90362538e-01, 9.38174465e-01],
        [2.31371485e-01, 2.36788755e-01, 4.60512137e-01, 7.07495229e-01]]])

In [33]:
zeros = np.append(zeros,[3,4])
zeros = np.insert(zeros , 2 , 1)
zeros

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 3., 4., 3., 4., 3., 4., 3., 4.,
       3., 4.])

In [34]:
np.delete(data,0,axis = 1)

array([[[0.4889169 , 0.58120092, 0.68812814, 0.73745315],
        [0.07879824, 0.11511485, 0.35241031, 0.35594832]],

       [[0.51819345, 0.85084378, 0.89036254, 0.93817447],
        [0.23137149, 0.23678876, 0.46051214, 0.70749523]]])

In [35]:
np.save("data",data)